# このプラグインのon・offを設定出来ます。
# (true = on false = off)
plugin-enable: false

# ServerList
# この機能をオンにする前に必ずTOKENを入力してください。
serverlist-enable: false
serverlist-token: ""

# プレイヤーの名前に空白があった場合にアンダーバーに変換します。(trueにする事を推奨)
player-namefix: false

